# Generated by Django 4.2 on 2023-04-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Эмэйл')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон номер')),
                ('payment_id', models.BigIntegerField(null=True)),
                ('payment_status', models.IntegerField(null=True)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='surur.tour', verbose_name='Заголовок тура')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
