# Generated by Django 4.2 on 2023-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Заголовок')),
                ('image', models.FileField(upload_to='category_photo/', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image1', models.ImageField(null=True, upload_to='photo_tour/', verbose_name='Фото Тура')),
                ('image2', models.ImageField(null=True, upload_to='photo_tour/', verbose_name='Фото Тура')),
                ('image3', models.ImageField(null=True, upload_to='photo_tour/', verbose_name='Фото Тура')),
                ('image4', models.ImageField(null=True, upload_to='photo_tour/', verbose_name='Фото Тура')),
                ('watched', models.IntegerField(default=True, verbose_name='Просмотры')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
    ]
